import Head from "next/head";
import TodoCheck from "@/components/TodoCheck";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import { useRouter } from "next/router";
import { isUserAuthenticated } from "@/utils/helper";
import { useEffect } from "react";

export default function Home() {
  const router = useRouter();

  //Authenticating user on main page
  //Navigate to Main page or sigin depending on status
  useEffect(() => {
    const userAuthenticated = isUserAuthenticated();
    if (!userAuthenticated) router.push("/login");
  }, []);
      
  return (
    <>
      <Head>
        <title>Next Todo App</title>
        <meta name="Todo App" content="Generated by MB's Technologies" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Provider store={store}>
          <TodoCheck />
        </Provider>
      </main>
    </>
  );
}
