import Head from "next/head";
import DashboardScreen from "@/components/DashboardScreen";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import { useRouter } from "next/router";
import { isUserAuthenticated } from "@/utils/helper";
import { useEffect, useState } from "react";
import { Login } from "@mui/icons-material";
import SignIn from "./login";

export default function Home() {
  const [authenticated, setAuthenticated] = useState(false)

  //Authenticating user on main page
  //Navigate to Main page or sigin depending on status

  useEffect(() => {
      setAuthenticated(isUserAuthenticated());
  }, []);
      
  return (
    <>
      <Head>
        <title>Next Todo App</title>
        <meta name="Todo App" content="Generated by MB's Technologies" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Provider store={store}>
          {authenticated ? <DashboardScreen /> : <SignIn />}
        </Provider>
    </>
  );
}
